### ISSUE TITLE
Hi issue found with mobile app of zen 

### ISSUE THREAD

**Issue by Cryptonewsmedia** [HorizenOfficial/zencash-mobile#102]
The qr code not responding with desktops wallet . It feels as a separate cold storage wallet . It responded to an online zencash as I put an address , tho it did not register as transaction happening on zen desktop through zenonlineclaim

**Comment by angievi** [comment]
Hi @Cryptonewsmedia , could you please open a ticket here: https://support.horizen.global/ this way our support team can give you a faster response on your issue. thanks in advance!

**Comment by uanl979** [comment]
hey there @Cryptonewsmedia 

There is no current compatibility of QRs for our products, we already have this issue already noticed. 
In the future, we are going to be making sphere mobile which is going to be fixing this issue. As of now, we have been limited in resources and we do not have defined date of when this is going to happen. Please be patient and I'll keep you on the loop. 

In the meantime you can use a QR scanner application for Android, for example this one has good reviews and it works with Sphere QR codes. This will help you to copy the address to your phone, for then to be pasted on the mobile version for your wallet.

https://play.google.com/store/apps/details?id=com.apple.qrcode.reader

Regards

**Comment by Cryptonewsmedia** [comment]
ok.confirmed.solved
